Chris
Bitwise-CSUMB/Project2CST363 pull request #6
Opened 2023-02-06 07:22 UTC by cmcmichael-csumb

Implemented patient get, show, and edit pages. All values that require input checking are run through the InputVerifier class.

> Added  verifyIdField method. Basically makes sure there's no symbols in it and that the id is smaller than the max int size to prevent possible overflow.

> Get, show, and edit pages tested with invalid inputs. I don't think I missed any but it's totally possible.

2023-02-06 19:47 UTC, Jake-CSUMB commented
Looks good - I've made a few minor fixes: please review #7.

2023-02-06 19:51 UTC, Jake-CSUMB requested changes
Looks good - I've made a few minor fixes: please review https://github.com/Bitwise-CSUMB/Project2CST363/pull/7.

2023-02-06 22:15 UTC, Jake-CSUMB approved these changes

2023-02-07 03:12 UTC, jeremiahmcgrath approved these changes

2023-02-07 03:12 UTC, merged